# Generated by Django 3.2.25 on 2025-05-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Upload a poster/photo for this event', null=True, upload_to='event_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('location', models.CharField(max_length=200)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('available_tickets', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
    ]
