# Generated by Django 3.2.25 on 2025-05-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20250503_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='available_tickets',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
